### ISSUE TITLE
Languages Support

### ISSUE THREAD

**Issue by Yodart** [apptreesoftware/flutter_calendar#54]
Does the calendar support languages other than english? Is the some "locale" method that i can place the user's location and the calendar would display the according language.

**Comment by ShenQingchuan** [comment]
Yes, I would like to apply for this function as well.
I found that the most important point is that in "package:flutter_calendar/flutter_calendar.dart", every date (or month) strings are just built from the method called "DateFormat()"

then I Ctrl+clicked it to find out what is it from...
the result is:  in "package:date_utils/date_utils.dart" those "DateFormat" are from something like "MMMM yyyy", so THESE RESTRICT make output string, and they are only in English...

It seems like that this issue is something about the source code of "date_utils.dart" 
maybe can't be solved by us...
