### ISSUE TITLE
Bug: The calendar repeats some months (JULY - JULY and so on)

### ISSUE THREAD

**Issue by luigifaticoso** [apptreesoftware/flutter_calendar#8]
The calendar shows me two consecutive July months. Have you encountered this problem? 

I've managed to change Weekdays name,
 how can i put monday as first day?
and how can i replace Months name so that they are italians? switching to italian language doesn't work

**Comment by luigifaticoso** [comment]
Any updates? What about the pull request? Come on, it's the best calendar I've tried for flutter!

**Comment by CzarLazar** [comment]
I had the same problem and resolved it by replacing 

`today = Utils.nextMonth(today);`

with

`today = new DateTime(today.year, today.month + 1); `

in the `void nextMonth()` function in `flutter_calendar.dart`.

I know this is more a workaraound than a solution, but it works.

ps This is my first comment ever on GitHub, if my comment isn't appropriate please feel free to tell me why :)

**Comment by gedw99** [comment]
First comment on GitHub ever anywhere ?

**Comment by Eternali** [comment]
Hey, I've got the same issue and I think I've found the problem.
The quick fix is to just modify the Utils.previousMonth and Utils.nextMonth methods to return a new date with the day set to some value deep into the month.

But I believe the root of the issue is in how the months are rendered out, some of the months have an extra row of days at the top (from the month before) that might be screwing some things up. I made a fix for it, but it seems like the calendar grid has to be a certain height for the ExpansionCrossFade to work. So that's what I'm trying to fix now.
I've forked the repo if anyone wants to see the progress.

**Comment by arvanus** [comment]
You can use this fork for now: https://github.com/yathit/flutter_calendar
If you need dart 2 support, you can use my fork (forked from yathit):
https://github.com/arvanus/flutter_calendar while the owner doesn't merge here.

**Comment by Eternali** [comment]
If anyone is still struggling with this I have forked both [flutter_calendar](https://github.com/eternali/flutter_calendar) and [date_utils](https://github.com/eternali/date_utils) and I think I pretty much have all the breaking bugs fixed (thanks to [zachtib's fork](https://github.com/zachtib/flutter_calendar) for fixing the painting issues).
I also made some additions like adding support for ticks (similar to [small_calendar](https://pub.dartlang.org/packages/small_calendar) and changing the way date highlighting works.

Anyways, it is still a work in progress, but it works for me.

**Comment by arvanus** [comment]
@Eternali you need to fix your pubspec.yaml file.
```
date_utils:
path: ../date_utils
```

**Comment by ericwindmill** [comment]
@luigifaticoso this is fixed, sorry for taking so long. @zacktib found the issues.
